#!/usr/bin/php
<?php
chdir(__DIR__);
$data = file_get_contents('tarallo-backend' . DIRECTORY_SEPARATOR . 'database-data.sql');
$lines = preg_split('/[\n\r]/', $data, -1, PREG_SPLIT_NO_EMPTY);
//$resultjs = 'let features = new Map();'.PHP_EOL;
$resultjs = '// BEGIN GENERATED CODE' . PHP_EOL;
$resultphp = "\t// BEGIN GENERATED CODE" . PHP_EOL . "\tconst features = [" . PHP_EOL;

$block = 0;
$features = [];
echo 'Found ' . count($lines) . ' lines' . PHP_EOL;
foreach($lines as $line) {
	/** @noinspection SqlNoDataSourceInspection */
	$wut = 'INSERT INTO `Feature`';
	if(substr($line, 0, strlen($wut)) === $wut) {
		$block = 1;
		continue;
	}
	/** @noinspection SqlNoDataSourceInspection */
	$wut = 'INSERT INTO `FeatureValue`';
	if(substr($line, 0, strlen($wut)) === $wut) {
		$block = 2;
		continue;
	}
	if($block === 0) {
		continue;
	} else {
		$boom = explode(',', $line);
		if(count($boom) < 3) {
			continue;
		}
		if(substr(trim($boom[0]), 0, 2) == '--') {
			continue;
		}
		if($block === 1) {
			$id = substr($boom[0], 2);
			$feature = substr($boom[1], 2, strlen($boom[1]) - 3);
			$type = substr($boom[2], 1, 1);

			if($type === '2') {
				$resultjs .= 'Features.list.set(\'' . $feature . '\', new Set({REPLACE' . $id . '}));' . PHP_EOL;
			} else {
				$resultjs .= 'Features.list.set(\'' . $feature . '\', null);' . PHP_EOL;
			}

			switch($type) {
				case '0':
					$resultphp .= "\t\t'$feature' => self::STRING," . PHP_EOL;
					break;
				case '1':
					$resultphp .= "\t\t'$feature' => self::INTEGER," . PHP_EOL;
					break;
				case '2':
					$resultphp .= "\t\t'$feature' => [{REPLACE$id}]," . PHP_EOL;
					break;
				case '3':
					$resultphp .= "\t\t'$feature' => self::DOUBLE," . PHP_EOL;
					break;
			}

			$features[$id] = [];

			echo 'Feature: ' . $id . ':' . $feature . ':' . $type . PHP_EOL;
		} else if($block === 2) {
			if(count($boom) === 3) {
				$distance = 5;
			} else {
				$distance = 4;
			}
			$id = substr($boom[0], 2);
			$value = substr($boom[2], 2, strlen($boom[2]) - $distance);

			$features[$id][] = $value;

			echo 'Value: ' . $id . ':' . $value . PHP_EOL;
		} else {
			echo 'Lolwut?' . PHP_EOL;
		}
	}
}

foreach($features as $id => $values) {
	$arrayjs = '[';
	$arrayphp = '';
	foreach($values as $value) {
		$arrayjs .= '\'' . $value . '\', ';
		$arrayphp .= "'$value' => true, ";
	}
	$arrayjs = substr($arrayjs, 0, strlen($arrayjs) - 2);
	$arrayphp = substr($arrayphp, 0, strlen($arrayphp) - 2); // trailing commas are valid in PHP, but this looks nices
	$arrayjs .= ']';
	$resultjs = str_replace('{REPLACE' . $id . '}', $arrayjs, $resultjs);
	$resultphp = str_replace('{REPLACE' . $id . '}', $arrayphp, $resultphp);
}
$resultjs .= '// END GENERATED CODE';
$resultphp .= "\t];" . PHP_EOL . "\t// END GENERATED CODE";

// Safer alternative:
//file_put_contents('features.generated.js', $resultjs);
//echo 'Done. Run "cat features.generated.js >> tarallo-frontend/js/features.js" and manually merge the file'.PHP_EOL;

$js = file_get_contents('tarallo-frontend' . DIRECTORY_SEPARATOR . 'js' . DIRECTORY_SEPARATOR . 'features.js');

$piecesjs = explode('// BEGIN GENERATED CODE' . PHP_EOL, $js, 2);
if(count($piecesjs) < 2) {
	echo 'Cannot find // BEGIN GENERATED CODE (followed by a newline in current platform format, which may be the problem) in tarallo-frontend/js/features.js' . PHP_EOL;
	exit(1);
}

$piecesjs2 = explode('// END GENERATED CODE', $js, 2);
if(count($piecesjs2) < 2) {
	echo 'Cannot find // END GENERATED CODE in tarallo-frontend/js/features.js' . PHP_EOL;
	exit(1);
}

$php = file_get_contents('tarallo-backend' . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Feature.php');

$piecesphp = explode("\t// BEGIN GENERATED CODE" . PHP_EOL, $php, 2);
if(count($piecesphp) < 2) {
	echo 'Cannot find // BEGIN GENERATED CODE (indented and followed by a newline in current platform format, which may be the problem) in tarallo-backend/src/Feature.php' . PHP_EOL;
	exit(1);
}

$piecesphp2 = explode("\t// END GENERATED CODE", $php, 2);
if(count($piecesphp2) < 2) {
	echo 'Cannot find indented // END GENERATED CODE in tarallo-backend/src/Feature.php' . PHP_EOL;
	exit(1);
}

file_put_contents('tarallo-frontend' . DIRECTORY_SEPARATOR . 'js' . DIRECTORY_SEPARATOR . 'features.js',
	$piecesjs[0] . $resultjs . $piecesjs2[1]);
file_put_contents('tarallo-backend' . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Feature.php',
	$piecesphp[0] . $resultphp . $piecesphp2[1]);
echo 'Done. Check "tarallo-frontend/js/features.js" and "tarallo-backend/src/Feature.php" and commit changes' . PHP_EOL;
